### ISSUE TITLE
RendererBase has no member named renderer_ 

### ISSUE THREAD

**Issue by krismz** [SCIInstitute/Seg3D#122]
While compiling on Linux, see error class Core::RendererBase has no member named renderer_

**Comment by krismz** [comment]
This is due to an error introduced by the #118 fix, that wasn't tested until trying to compile on linux.  Fixed under that issue, closing this issue.
